### ISSUE TITLE
.demuxToBuffers() error

### ISSUE THREAD

**Issue by Nurutomo** [ApeironTsuka/node-webpmux#11]
Im using webp file from https://api.xteam.xyz/attp?file&text=test

`await img.demuxToBuffers()`

Array of rejected promises
```
Error: Frame has no VP8/VP8L?
    at Image.#demuxFrame (F:\wabot-aq\node_modules\node-webpmux\webp.js:480:20)
    at Image.#demuxFrameBuffer (F:\wabot-aq\node_modules\node-webpmux\webp.js:461:28)
    at Image.#demux (F:\wabot-aq\node_modules\node-webpmux\webp.js:497:46)
    at Image.demuxToBuffers (F:\wabot-aq\node_modules\node-webpmux\webp.js:643:85)
    at WAConnection.eval (eval at handler (F:\wabot-aq\plugins\exec.js:15:16), <anonymous>:3:30)
    at WAConnection.handler (F:\wabot-aq\plugins\exec.js:16:26)
    at WAConnection.handler (F:\wabot-aq\handler.js:245:26)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
 ```

**Comment by ApeironTsuka** [comment]
Thanks for this. Seems my testing is still not quite up to par. I'll also push this to npm, as it's a fairly serious oversight.
